name: pywr_test
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - networkx
  - numpy
  - cython
  - glpk
  - pandas
  - h5py
  - pytables
  - matplotlib
  - geopandas
  - pyreadr